<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgfMo3F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgfMo3F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWgfMo3F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWgfMo3F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWgfMo3F\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WgfMo3F',
    'container.build_id' => 'e4c64ac8',
    'container.build_time' => 1580773262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgfMo3F');
