<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN4IlWBB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN4IlWBB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN4IlWBB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN4IlWBB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN4IlWBB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N4IlWBB',
    'container.build_id' => 'a599edd6',
    'container.build_time' => 1580843729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN4IlWBB');
